name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  authorize:
    name: Authorize
    runs-on: macos-latest
    steps:
      - name: ${{ github.actor }} permission check to do a release
        uses: octokit/request-action@89697eb6635e52c6e1e5559f15b5c91ba5100cb0 # v2.1.9
        with:
          route: GET /repos/:repository/collaborators/${{ github.actor }}
          repository: ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Release
    runs-on: macos-15
    needs: [authorize]
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@ed7a3b1fda3918c0306d1b724322adc0b8cc0a90 # v1
        with:
          xcode-version: '16.4'

      - name: Validate Podfile
        run: pod lib lint --allow-warnings --verbose
      
      - name: Zip xcframework
        working-directory: Sources
        run: zip -r -y AmplitudeEngagementSwift.xcframework.zip AmplitudeEngagementSwift.xcframework

      - name: Publish to CocoaPods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod trunk push AmplitudeEngagementSwift.podspec --allow-warnings
